name: Example Workflow

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

# https://github.com/octokit/request-action
    steps:
      - name: Dump git and context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # https://github.com/octokit/request-action#usage b
      - name: Link to toolz
        uses: octokit/request-action@v2.x
        id: create_check_suite
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: $ {{ github.repository_owner }}
          repo: $ {{ github.event.repository.name }}
          name: "Test check run"
          head_sha: ${{ github.sha }}
          output: | # The | is significant!
            title: Data-Science Toolz Application
            summary: A link to the toolz- https://toolz.7learnings.com/streamlit/?run_identifier=${{ env.RUN_ID }}&project=${{ env.PROJECT }}
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}