name: Example Workflow

on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Annotate Checks
      uses: agyemanjp/ci-checks-action@2.0.3
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        checks: '[
            {
              "name": "lint",
              "fileName": ".lint-report.json",
              "prChangesOnly": true
            },
            {
              "name": "test",
              "fileName": ".test-report.json",
              "prChangesOnly": false
            }
          ]'