name: "github-checks"
on: [push]

jobs:
  # make sure the action works on a clean machines without building

  ## Basic
  test_basic_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link to toolz app
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          actions: 
            do_this:
              label: Fix this
              description: Let us fix that for you
              identifier: fix_errors