name: Example Workflow

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

# https://github.com/octokit/request-action
    steps:

      - name: Dump GitHub context
        id: a
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        id: b
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"


      - name: using github scripts 
        uses: actions/github-script@v3
        with:
          debug: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github..checks.listForRef({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.event.repository.name }}',
              ref: '${{ github.ref }}',
              check_name: 'run'
            });

      # - name: using github scripts 
      #   uses: actions/github-script@v3
      #   with:
      #     debug: true
      #     github-token: ${{secrets.GITHUB_TOKEN}}
      #     script: |
      #       github.actions.getJobForWorkflowRun({
      #         owner: '${{ github.repository_owner }}',
      #         repo: '${{ github.event.repository.name }}',
      #         job_id: ${{ github.run_id }}
      #       });
      - name: ttt
        id: toolz
        # uses: octokit/request-action@v2.x
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   STEPS_CONTXT: ${{ toJSON(steps) }}
        #   full_repo: ${{ github.repository }}
        #   run_id: ${{ github.run_id }}
        # run: echo "$STEPS_CONTXT"
        run: |
          export CHECK_SUITE_ID=$(curl --fail --silent --show-error \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}" | jq ".check_suite_id") 
          export CHECK_SUITE_LAST_RUN_ID=$(curl --fail --silent --show-error \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/check-suites/${CHECK_SUITE_ID}/check-runs" | jq ".check_runs[-1].id")
          echo $CHECK_SUITE_LAST_RUN_ID
          echo "CHECK_SUITE_LAST_RUN_ID=$CHECK_SUITE_LAST_RUN_ID" >> $GITHUB_ENV
        
        
        # CHECK_SUITE_RUN_URL="${CHECK_SUITE_URL}/check-runs"
        # echo "CHECK_SUITE_RUN_URL=$CHECK_SUITE_RUN_URL" >> $GITHUB_ENV
        # echo $CHECK_SUITE_RUN_URL
        # echo ${{ env.CHECK_SUITE_RUN_URL }}

        # curl --fail --silent --show-error
        # -H "Accept: application/vnd.github.v3+json"
        # "https://api.github.com/repos/${{ github.repository }}/actions/check-suites/${CHECK_SUITE_ID}/check-runs"
        # curl \
        # -H "Accept: application/vnd.github.v3+json" \
        # https://api.github.com/repos/${{ github.repository }}/actions/jobs/${{ github.run_id }}
        # with:
        #   route: GET /repos/{full_repo}/actions/runs/{run_id}
        #   full_repo: ${{ github.repository }}
        #   run_id: ${{ github.run_id }}
        #   name: "Toolz"
        #   head_sha: ${{ github.sha }}
        #   output: |


      - name: Data-Science Toolz Link
        # uses: octokit/request-action@v2.x
        id: toolz_check_suite
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          curl \
          -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/check-runs/${{ env.CHECK_SUITE_LAST_RUN_ID }} \
          -d '{"name":"HALLOOOOOOOO"}'
        # with:
        #   route: PATCH /repos/{full_repo}/check-runs/{check_run_id}
        #   full_repo: ${{ github.repository }}
        #   check_run_id: ${{ env.CHECK_SUITE_LAST_RUN_ID }}
        #   name: "Toolz"
        #   head_sha: ${{ github.sha }}
        #   output: |
        #     title: Data-Science Toolz Application
        #     summary: A link to the toolz- https://toolz.7learnings.com/streamlit/?module=compare_forecasts&run_identifier=${{ env.RUN_ID }}&project=${{ env.PROJECT }}