name: Example Workflow

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

# https://github.com/octokit/request-action
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      id: checkoutrepo
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo ${{github}}"
    - name: Annotate Checks
      uses: octokit/request-action@v2.x
      id: create_check_suite
      with:
        route: POST /repos/{owner}/{repo}/check-runs
        owner: jyotirmay123
        repo: learning_git_action
        name: "Test check run"
        head_sha: ${{ github.sha }}
        output: | # The | is significant!
          title: Test check run title
          summary: A summary of the test check run. More here https://toolz.7learnings.com or [here](https://toolz.7learnings.com)
          action_url:
              url: https://toolz.7learnings.com
          images:
            - alt: Test image
              image_url: https://jyotirmays.com/img/portfolio/quicknat.jpg
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo checks-suite output: ${{ steps.create_check_suite.outputs.data }}"