name: Example Workflow

on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      id: checkoutrepo
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Annotate Checks
      uses: octokit/request-action@v2.x
      id: create_check_suite
      with:
        route: POST /repos/{owner}/{repo}/check-runs
        owner: jyotirmay123
        repo: learning_git_action
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: "echo checks-suite output: ${{ steps.create_check_suite.outputs.data }}"