name: learn-github-actions
on: 
  schedule: [{cron: '00 06 * * *'}]
  pull_request: { branches: [master, main] }
  push: { branches: [master, main] }
  issue_comment:
    types: [created]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Jobs and status above
        run: |
          echo "hi"

      - name: Post status back to git
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: " \"<https://github.com/7Learnings/repo/actions/runs/${{github.run_id | github.workflow }}> run ${{ job.status }} (event: ${{ github.event_name }})\" "
            })